version: '3.8'

services:
  movie_service:
    build: ./movie_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./movie_service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://postgres:Wefv9164yuik@movie_db/movie_db_dev
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/

  movie_db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Wefv9164yuik
      - POSTGRES_DB=movie_db_dev

  cast_service:
    build: ./cast_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./cast_service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://postgres:Wefv9164yuik@cast_db/cast_db_dev

  cast_db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data_cast:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Wefv9164yuik
      - POSTGRES_DB=cast_db_dev

  nginx:
      image: nginx:latest
      ports:
        - "8080:8080"
      volumes:
        - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - cast_service
        - movie_service

volumes:
  postgres_data_movie:
  postgres_data_cast: